/**
 * This file is autogenerated.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  31337: {
    FHECounter: {
      address: "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
      abi: [
        {
          type: "function",
          name: "confidentialProtocolId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decrement",
          inputs: [
            {
              name: "inputEuint32",
              type: "bytes32",
              internalType: "externalEuint32",
            },
            {
              name: "inputProof",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "euint32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "increment",
          inputs: [
            {
              name: "inputEuint32",
              type: "bytes32",
              internalType: "externalEuint32",
            },
            {
              name: "inputProof",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "error",
          name: "SenderNotAllowedToUseHandle",
          inputs: [
            {
              name: "handle",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ZamaProtocolUnsupported",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 14,
    },
  },
  11155111: {
    FHECounter: {
      address: "0x3CC73d13B88cbE6d31Ff2Fa8c5A7b12ef68f96c9",
      abi: [
        {
          type: "function",
          name: "confidentialProtocolId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decrement",
          inputs: [
            {
              name: "inputEuint32",
              type: "bytes32",
              internalType: "externalEuint32",
            },
            {
              name: "inputProof",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "euint32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "increment",
          inputs: [
            {
              name: "inputEuint32",
              type: "bytes32",
              internalType: "externalEuint32",
            },
            {
              name: "inputProof",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "error",
          name: "SenderNotAllowedToUseHandle",
          inputs: [
            {
              name: "handle",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ZamaProtocolUnsupported",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10678430,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
