/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./FHECounter.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { FHECounter } from "~~/contracts/FHECounter";`
 */
import { FHECounter as FHECounter_LOCAL } from "./FHECounter.local";
import type { ContractDeployment } from "~~/utils/contract";

const REMOTE = {
  11155111: {
    address: "0xB9AA7F7E25c91D7004CcEb71c712Cd58a5fDFb03",
    abi: [
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "decrement",
        inputs: [
          {
            name: "inputEuint32",
            type: "bytes32",
            internalType: "externalEuint32",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "getCount",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "increment",
        inputs: [
          {
            name: "inputEuint32",
            type: "bytes32",
            internalType: "externalEuint32",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 10723515,
  },
} as const;

export const FHECounter = {
  ...REMOTE,
  ...FHECounter_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
