/**
 * Generates packages/nextjs/contracts/deployedContracts.ts from foundry
 * build output + broadcast receipts.
 *
 * Inputs:
 *   packages/foundry/out/<Name>.sol/<Name>.json              — compiled ABI
 *   packages/foundry/broadcast/.../<chainId>/run-latest.json — deployed addr+block
 *
 * Output:
 *   packages/nextjs/contracts/deployedContracts.ts
 */
import * as fs from "fs";
import * as path from "path";
import * as prettier from "prettier";
import { getAddress } from "viem";

const REPO_ROOT = path.resolve(__dirname, "..");
const FOUNDRY_DIR = path.join(REPO_ROOT, "packages/foundry");
const OUT_DIR = path.join(FOUNDRY_DIR, "out");
const BROADCAST_DIR = path.join(FOUNDRY_DIR, "broadcast");
const TARGET_FILE = path.join(REPO_ROOT, "packages/nextjs/contracts/deployedContracts.ts");

type Deployment = {
  address: `0x${string}`;
  deployedOnBlock: number;
};

/** Walk broadcast/ for `CREATE` txs, grouped by chainId → contract name. */
function collectDeployments(): Record<number, Record<string, Deployment>> {
  const out: Record<number, Record<string, Deployment>> = {};
  if (!fs.existsSync(BROADCAST_DIR)) return out;

  for (const scriptDir of fs.readdirSync(BROADCAST_DIR)) {
    const scriptPath = path.join(BROADCAST_DIR, scriptDir);
    if (!fs.statSync(scriptPath).isDirectory()) continue;

    for (const chainIdStr of fs.readdirSync(scriptPath)) {
      const chainPath = path.join(scriptPath, chainIdStr);
      const runLatest = path.join(chainPath, "run-latest.json");
      if (!fs.existsSync(runLatest)) continue;

      const chainId = Number(chainIdStr);
      const run = JSON.parse(fs.readFileSync(runLatest, "utf8"));
      const receipts: Array<{ blockNumber: string; transactionHash: string }> = run.receipts ?? [];
      const receiptByHash = new Map(receipts.map(r => [r.transactionHash, r]));

      for (const tx of run.transactions ?? []) {
        if (tx.transactionType !== "CREATE" || !tx.contractName || !tx.contractAddress) continue;
        const receipt = receiptByHash.get(tx.hash);
        const deployedOnBlock = receipt ? parseInt(receipt.blockNumber, 16) : 0;
        out[chainId] ??= {};
        // Foundry writes lowercase addresses; Zama's relayer SDK requires EIP-55
        // checksummed addresses (isChecksummedAddress() check in createRelayerEncryptedInput).
        out[chainId][tx.contractName] = {
          address: getAddress(tx.contractAddress),
          deployedOnBlock,
        };
      }
    }
  }
  return out;
}

/** Read the compiled ABI for a contract from out/. */
function readAbi(contractName: string): unknown[] {
  const artifactPath = path.join(OUT_DIR, `${contractName}.sol`, `${contractName}.json`);
  if (!fs.existsSync(artifactPath)) {
    throw new Error(`Missing foundry artifact: ${artifactPath} — run 'forge build' in packages/foundry`);
  }
  const { abi } = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  return abi;
}

async function main() {
  const deployments = collectDeployments();
  if (Object.keys(deployments).length === 0) {
    console.warn("No deployments found in packages/foundry/broadcast/");
  }

  const contractsByChain: Record<string, Record<string, unknown>> = {};
  for (const [chainIdStr, contracts] of Object.entries(deployments)) {
    contractsByChain[chainIdStr] = {};
    for (const [name, dep] of Object.entries(contracts)) {
      contractsByChain[chainIdStr][name] = {
        address: dep.address,
        abi: readAbi(name),
        inheritedFunctions: {},
        deployedOnBlock: dep.deployedOnBlock,
      };
    }
  }

  // Chain IDs must be numeric keys in the generated TS (the consumer type narrows on `number`).
  const serialized = JSON.stringify(contractsByChain, null, 2).replace(/^(\s*)"(\d+)":/gm, "$1$2:");

  const body = `/**
 * This file is autogenerated.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = ${serialized} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

  const formatted = await prettier.format(body, { parser: "typescript" });
  fs.writeFileSync(TARGET_FILE, formatted);
  console.log(`✓ wrote ${path.relative(REPO_ROOT, TARGET_FILE)}`);
  for (const [chainId, contracts] of Object.entries(deployments)) {
    for (const [name, dep] of Object.entries(contracts)) {
      console.log(`  ${chainId} ${name} @ ${dep.address} (block ${dep.deployedOnBlock})`);
    }
  }
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
